# -*- coding: UTF-8 -*- 
# @time: 2021/2/25 10:18
# @file: Tanslator.py
# @Author: YoungYuan
# http://fanyi.youdao.com/

"""
Some of the formdata elements of Youdao translation are generated by JS(fanyi.min.js:1), 
So we need to reconstruct JS function with Python

var r = function(e) {
    var t = n.md5(navigator.appVersion)  /** 将浏览器头加密 */
      , r = "" + (new Date).getTime()  /** 时间戳13位，字符串形式 */
      , i = r + parseInt(10 * Math.random(), 10);  /** 时间戳末尾加1位9以内的随机整数 */
    return {
        ts: r,
        bv: t,  /** 不变，故无需处理 */
        salt: i,
        sign: n.md5("fanyideskweb" + e + i + "Tbh5E8=q6U3EXe+&L[4c@")  /** 哈希加密16进制，其中e代表接收的文本 */
    }
};
"""

import time
import requests
import random
from hashlib import md5


class YouDao(object):
    def __init__(self, text):
        self.url = 'http://fanyi.youdao.com/translate_o?smartresult=dict&smartresult=rule'
        self.headers = {
            'Accept': 'application/json, text/javascript, */*; q=0.01',
            'Accept-Encoding': 'gzip, deflate',
            'Accept-Language': 'zh-CN,zh;q=0.9',
            'Connection': 'keep-alive',
            'Content-Length': '238',
            'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8',
            'Cookie': 'OUTFOX_SEARCH_USER_ID=-794918314@10.169.0.83; OUTFOX_SEARCH_USER_ID_NCOO=1946612798.2516308; JSESSIONID=aaawJyiAusLFq_No5_wFx; ___rl__test__cookies=1614219848180',
            'DNT': '1',
            'Host': 'fanyi.youdao.com',
            'Origin': 'http://fanyi.youdao.com',
            'Referer': 'http://fanyi.youdao.com/',
            'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.192 Safari/537.36',
            'X-Requested-With': 'XMLHttpRequest',
        }
        self.formdata = {}
        self.text = text

    def generate_formdata(self):
        e = self.text
        r = str(int(time.time() * 1000))
        i = r + str(random.randint(0, 9))
        string = "fanyideskweb" + e + i + "Tbh5E8=q6U3EXe+&L[4c@"
        sign = md5(string.encode()).hexdigest()
        formdata = {
            'i': e,
            'from': 'AUTO',
            'to': 'AUTO',
            'smartresult': 'dict',
            'client': 'fanyideskweb',
            'salt': i,
            'sign': sign,
            'lts': r,
            'bv': '944514ecccca92923eaae9274b4d03fb',
            'doctype': 'json',
            'version': '2.1',
            'keyfrom': 'fanyi.web',
            'action': 'FY_BY_REALTlME',
        }
        return formdata

    def get_html(self):
        self.formdata = self.generate_formdata()
        response = requests.post(url=self.url, headers=self.headers, data=self.formdata).json()
        return response

    def run(self):
        try:
            results = self.get_html()
            if 'smartResult' not in results:
                results = results['translateResult'][0]
                result_list=[i['tgt'] for i in results]
                result = ''.join(result_list)
                return result
            else:
                results = results['smartResult']['entries']
                result_list = [i for i in results]
                result = ''.join(result_list)
                return result
        except:
            return 'None results'


if __name__ == '__main__':
    while True:
        input_text = input('Please enter the text to be translated (exit->00)：')
        if input_text == '00':
            print('Bye!')
            exit(0)
        app = YouDao(input_text)
        print(app.run())
